#include <stdint.h>
#include <stdlib.h>
#include <string.h>

typedef enum {
    MAVLINK_MSG_ID_HEARTBEAT                     = 0,
    MAVLINK_MSG_ID_SYS_STATUS                    = 1,
    MAVLINK_MSG_ID_SYSTEM_TIME                   = 2,
    MAVLINK_MSG_ID_PING                          = 4,
    MAVLINK_MSG_ID_SET_MODE                      = 11,
    MAVLINK_MSG_ID_PARAM_REQUEST_READ            = 20,
    MAVLINK_MSG_ID_PARAM_REQUEST_LIST            = 21,
    MAVLINK_MSG_ID_PARAM_VALUE                   = 22,
    MAVLINK_MSG_ID_PARAM_SET                     = 23,
    MAVLINK_MSG_ID_GPS_RAW_INT                   = 24,
    MAVLINK_MSG_ID_GPS_STATUS                    = 25,
    MAVLINK_MSG_ID_SCALED_IMU                    = 26,
    MAVLINK_MSG_ID_RAW_IMU                       = 27,
    MAVLINK_MSG_ID_RAW_PRESSURE                  = 28,
    MAVLINK_MSG_ID_SCALED_PRESSURE               = 29,
    MAVLINK_MSG_ID_ATTITUDE                      = 30,
    MAVLINK_MSG_ID_ATTITUDE_QUATERNION           = 31,
    MAVLINK_MSG_ID_LOCAL_POSITION_NED            = 32,
    MAVLINK_MSG_ID_GLOBAL_POSITION_INT           = 33,
    MAVLINK_MSG_ID_RC_CHANNELS_SCALED            = 34,
    MAVLINK_MSG_ID_RC_CHANNELS_RAW               = 35,
    MAVLINK_MSG_ID_SERVO_OUTPUT_RAW              = 36,
    MAVLINK_MSG_ID_MISSION_ITEM                  = 39,
    MAVLINK_MSG_ID_MISSION_REQUEST               = 40,
    MAVLINK_MSG_ID_MISSION_SET_CURRENT           = 41,
    MAVLINK_MSG_ID_MISSION_CURRENT               = 42,
    MAVLINK_MSG_ID_MISSION_REQUEST_LIST          = 43,
    MAVLINK_MSG_ID_MISSION_COUNT                 = 44,
    MAVLINK_MSG_ID_MISSION_CLEAR_ALL             = 45,
    MAVLINK_MSG_ID_MISSION_ITEM_REACHED          = 46,
    MAVLINK_MSG_ID_MISSION_ACK                   = 47,
    MAVLINK_MSG_ID_SET_GPS_GLOBAL_ORIGIN         = 48,
    MAVLINK_MSG_ID_GPS_GLOBAL_ORIGIN             = 49,
    MAVLINK_MSG_ID_PARAM_MAP_RC                  = 50,
    MAVLINK_MSG_ID_MISSION_REQUEST_INT           = 51,
    MAVLINK_MSG_ID_RC_CHANNELS                   = 65,
    MAVLINK_MSG_ID_REQUEST_DATA_STREAM           = 66,
    MAVLINK_MSG_ID_DATA_STREAM                   = 67,
    MAVLINK_MSG_ID_MANUAL_CONTROL                = 69,
    MAVLINK_MSG_ID_MISSION_ITEM_INT              = 73,
    MAVLINK_MSG_ID_VFR_HUD                       = 74,
    MAVLINK_MSG_ID_COMMAND_LONG                  = 76,
    MAVLINK_MSG_ID_COMMAND_ACK                   = 77,
    MAVLINK_MSG_ID_ATTITUDE_TARGET               = 83,
    MAVLINK_MSG_ID_SAFETY_ALLOWED_AREA           = 85,
    MAVLINK_MSG_ID_BATTERY_STATUS                = 147,
    MAVLINK_MSG_ID_MAX                           = 255
} mavlink_msgid_t;

const char *mavlink_msg_names[] = {
    [MAVLINK_MSG_ID_HEARTBEAT]            = "HEARTBEAT",
    [MAVLINK_MSG_ID_SYS_STATUS]           = "SYS_STATUS",
    [MAVLINK_MSG_ID_SYSTEM_TIME]          = "SYSTEM_TIME",
    [MAVLINK_MSG_ID_PING]                 = "PING",
    [MAVLINK_MSG_ID_SET_MODE]             = "SET_MODE",
    [MAVLINK_MSG_ID_PARAM_REQUEST_READ]   = "PARAM_REQUEST_READ",
    [MAVLINK_MSG_ID_PARAM_REQUEST_LIST]   = "PARAM_REQUEST_LIST",
    [MAVLINK_MSG_ID_PARAM_VALUE]          = "PARAM_VALUE",
    [MAVLINK_MSG_ID_PARAM_SET]            = "PARAM_SET",
    [MAVLINK_MSG_ID_GPS_RAW_INT]          = "GPS_RAW_INT",
    [MAVLINK_MSG_ID_GPS_STATUS]           = "GPS_STATUS",
    [MAVLINK_MSG_ID_SCALED_IMU]           = "SCALED_IMU",
    [MAVLINK_MSG_ID_RAW_IMU]              = "RAW_IMU",
    [MAVLINK_MSG_ID_RAW_PRESSURE]         = "RAW_PRESSURE",
    [MAVLINK_MSG_ID_SCALED_PRESSURE]      = "SCALED_PRESSURE",
    [MAVLINK_MSG_ID_ATTITUDE]             = "ATTITUDE",
    [MAVLINK_MSG_ID_ATTITUDE_QUATERNION]  = "ATTITUDE_QUATERNION",
    [MAVLINK_MSG_ID_LOCAL_POSITION_NED]   = "LOCAL_POSITION_NED",
    [MAVLINK_MSG_ID_GLOBAL_POSITION_INT]  = "GLOBAL_POSITION_INT",
    [MAVLINK_MSG_ID_RC_CHANNELS_SCALED]   = "RC_CHANNELS_SCALED",
    [MAVLINK_MSG_ID_RC_CHANNELS_RAW]      = "RC_CHANNELS_RAW",
    [MAVLINK_MSG_ID_SERVO_OUTPUT_RAW]     = "SERVO_OUTPUT_RAW",
    [MAVLINK_MSG_ID_MISSION_ITEM]         = "MISSION_ITEM",
    [MAVLINK_MSG_ID_MISSION_REQUEST]      = "MISSION_REQUEST",
    [MAVLINK_MSG_ID_MISSION_SET_CURRENT]  = "MISSION_SET_CURRENT",
    [MAVLINK_MSG_ID_MISSION_CURRENT]      = "MISSION_CURRENT",
    [MAVLINK_MSG_ID_MISSION_REQUEST_LIST] = "MISSION_REQUEST_LIST",
    [MAVLINK_MSG_ID_MISSION_COUNT]        = "MISSION_COUNT",
    [MAVLINK_MSG_ID_MISSION_CLEAR_ALL]    = "MISSION_CLEAR_ALL",
    [MAVLINK_MSG_ID_MISSION_ITEM_REACHED] = "MISSION_ITEM_REACHED",
    [MAVLINK_MSG_ID_MISSION_ACK]          = "MISSION_ACK",
    [MAVLINK_MSG_ID_SET_GPS_GLOBAL_ORIGIN]= "SET_GPS_GLOBAL_ORIGIN",
    [MAVLINK_MSG_ID_GPS_GLOBAL_ORIGIN]    = "GPS_GLOBAL_ORIGIN",
    [MAVLINK_MSG_ID_PARAM_MAP_RC]         = "PARAM_MAP_RC",
    [MAVLINK_MSG_ID_MISSION_REQUEST_INT]  = "MISSION_REQUEST_INT",
    [MAVLINK_MSG_ID_RC_CHANNELS]          = "RC_CHANNELS",
    [MAVLINK_MSG_ID_REQUEST_DATA_STREAM]  = "REQUEST_DATA_STREAM",
    [MAVLINK_MSG_ID_DATA_STREAM]          = "DATA_STREAM",
    [MAVLINK_MSG_ID_MANUAL_CONTROL]       = "MANUAL_CONTROL",
    [MAVLINK_MSG_ID_MISSION_ITEM_INT]     = "MISSION_ITEM_INT",
    [MAVLINK_MSG_ID_VFR_HUD]              = "VFR_HUD",
    [MAVLINK_MSG_ID_COMMAND_LONG]         = "COMMAND_LONG",
    [MAVLINK_MSG_ID_COMMAND_ACK]          = "COMMAND_ACK",
    [MAVLINK_MSG_ID_ATTITUDE_TARGET]      = "ATTITUDE_TARGET",
    [MAVLINK_MSG_ID_SAFETY_ALLOWED_AREA]  = "SAFETY_ALLOWED_AREA",
    [MAVLINK_MSG_ID_BATTERY_STATUS]       = "BATTERY_STATUS",
    [MAVLINK_MSG_ID_MAX]                  = ""
};

const char* mavlink_msg_id_to_str(int msgid) {
    if (msgid < 0 || msgid >= (int)(sizeof(mavlink_msg_names)/sizeof(mavlink_msg_names[0])) ||
        mavlink_msg_names[msgid] == NULL) {
        return "UNKNOWN";
    }
    return mavlink_msg_names[msgid];
}
